const container = document.querySelector('#sequencer');

export const references = {
	container,
	maxBars: 32,
	maxTics: 256, //32*8
	subdivision: 8,
	tracksLength: 10,
	startClass: 'started',
	currentClass: 'current',
	draggedClass: 'dragged',
	setSearchParam: 'set',
	tempoSearchParam: 'bpm',
	volumeSearchParam: 'vol',
	titleSearchParam: 'title',
	shareSearchParam: 'share',
	headUntitled: 'Morceau sans titre',
	bpm: container.querySelector('#combo_tempo span'),
	tempo: container.querySelector('#tempo'),
	title: container.querySelector('h1'),
	startButton: container.querySelector('#start'),
	resetButton: container.querySelector('#reset'),
	favoriteButton: container.querySelector('#combo_presets button'),
	shared: container.querySelector('#shared'),
	shareList: container.querySelector('#share .list'),
	sharedList: container.querySelector('#shared .list'),
	shareButton: container.querySelector('#share button[name="share"]'),
	checkBoxMaster: container.querySelector('#share legend input'),
	presetsSelection: container.querySelector('#combo_presets select'),
	settingsDialog: container.querySelector('#settings'),
	toast: container.querySelector('#toast'),
	toastMessage: container.querySelector('#toast p'),
	toastButton: container.querySelector('#toast button'),
	tics: container.getElementsByClassName('tic'),
	bars: container.getElementsByClassName('bars'),
	beats: container.getElementsByClassName('beat'),
	tracks: container.getElementsByClassName('track'),
	volumes: container.getElementsByClassName('volume'),
	dropzones: container.getElementsByClassName('dropzone'),
	instruments: container.getElementsByClassName('instrument'),
}