const container = document.querySelector('#sequencer');

export const references = {
	container,
	maxBars: 32,
	maxTics: 256, //32*8
	subdivision: 8,
	tracksLength: 10,
	startClass: 'started',
	currentClass: 'current',
	draggedClass: 'dragged',
	setSearchParam: 'set',
	tempoSearchParam: 'bpm',
	volumeSearchParam: 'vol',
	titleSearchParam: 'title',
	headUntitled: 'Morceau sans titre',
	bpm: container.querySelector('#bpm'),
	tempo: container.querySelector('#tempo'),
	title: container.querySelector('#title'),
	startButton: container.querySelector('#start'),
	resetButton: container.querySelector('#reset'),
	favoriteButton: container.querySelector('#favorite'),
	presetsSelection: container.querySelector('#presets'),
	settingsDialog: container.querySelector('#settings'),
	toast: container.querySelector('#toast'),
	toastMessage: container.querySelector('#toast_message'),
	toastButton: container.querySelector('#toast_button'),
	tics: container.getElementsByClassName('tic'),
	bars: container.getElementsByClassName('bars'),
	beats: container.getElementsByClassName('beat'),
	tracks: container.getElementsByClassName('track'),
	volumes: container.getElementsByClassName('volume'),
	dropzones: container.getElementsByClassName('dropzone'),
	instruments: container.getElementsByClassName('instrument'),
}